# Generated by Django 3.1 on 2021-10-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_contact_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
