# Generated by Django 3.1 on 2021-10-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
